// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/404.tsx";
import * as $_404_1 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_change_password from "./routes/api/change-password.ts";
import * as $api_exams from "./routes/api/exams.ts";
import * as $api_exams_id_ from "./routes/api/exams/[id].ts";
import * as $api_exams_index from "./routes/api/exams/index.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_payments_id_ from "./routes/api/payments/[id].ts";
import * as $api_payments_index from "./routes/api/payments/index.ts";
import * as $api_students from "./routes/api/students.ts";
import * as $api_students_id_ from "./routes/api/students/[id].ts";
import * as $api_students_index from "./routes/api/students/index.ts";
import * as $auth from "./routes/auth.ts";
import * as $exams_id_edit from "./routes/exams/[id]/edit.tsx";
import * as $exams_index from "./routes/exams/index.tsx";
import * as $exams_new from "./routes/exams/new.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $payments_id_edit from "./routes/payments/[id]/edit.tsx";
import * as $payments_index from "./routes/payments/index.tsx";
import * as $payments_new from "./routes/payments/new.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $statistics_index from "./routes/statistics/index.tsx";
import * as $students_id_ from "./routes/students/[id].tsx";
import * as $students_id_edit from "./routes/students/[id]/edit.tsx";
import * as $students_index from "./routes/students/index.tsx";
import * as $students_new from "./routes/students/new.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DarkModeToggle from "./islands/DarkModeToggle.tsx";
import * as $ExamsList from "./islands/ExamsList.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $MobileMenu from "./islands/MobileMenu.tsx";
import * as $PasswordChangeForm from "./islands/PasswordChangeForm.tsx";
import * as $PaymentsList from "./islands/PaymentsList.tsx";
import * as $StatisticsList from "./islands/StatisticsList.tsx";
import * as $StudentForm from "./islands/StudentForm.tsx";
import * as $StudentsList from "./islands/StudentsList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/404.tsx": $_404,
    "./routes/_404.tsx": $_404_1,
    "./routes/_app.tsx": $_app,
    "./routes/api/change-password.ts": $api_change_password,
    "./routes/api/exams.ts": $api_exams,
    "./routes/api/exams/[id].ts": $api_exams_id_,
    "./routes/api/exams/index.ts": $api_exams_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/payments/[id].ts": $api_payments_id_,
    "./routes/api/payments/index.ts": $api_payments_index,
    "./routes/api/students.ts": $api_students,
    "./routes/api/students/[id].ts": $api_students_id_,
    "./routes/api/students/index.ts": $api_students_index,
    "./routes/auth.ts": $auth,
    "./routes/exams/[id]/edit.tsx": $exams_id_edit,
    "./routes/exams/index.tsx": $exams_index,
    "./routes/exams/new.tsx": $exams_new,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/payments/[id]/edit.tsx": $payments_id_edit,
    "./routes/payments/index.tsx": $payments_index,
    "./routes/payments/new.tsx": $payments_new,
    "./routes/settings.tsx": $settings,
    "./routes/statistics/index.tsx": $statistics_index,
    "./routes/students/[id].tsx": $students_id_,
    "./routes/students/[id]/edit.tsx": $students_id_edit,
    "./routes/students/index.tsx": $students_index,
    "./routes/students/new.tsx": $students_new,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/DarkModeToggle.tsx": $DarkModeToggle,
    "./islands/ExamsList.tsx": $ExamsList,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/MobileMenu.tsx": $MobileMenu,
    "./islands/PasswordChangeForm.tsx": $PasswordChangeForm,
    "./islands/PaymentsList.tsx": $PaymentsList,
    "./islands/StatisticsList.tsx": $StatisticsList,
    "./islands/StudentForm.tsx": $StudentForm,
    "./islands/StudentsList.tsx": $StudentsList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
